stages:
  pack_light_1:
    cmd: python3 simulate_research.py pack_light_1
    deps:
      - simulate_research.py
    outs:
      - artifacts/pack_light_1.bin
    metrics:
      - metrics/pack_light_1.json:
          cache: false
    meta:
      cluster:
        workers:
          - HEC45803
        cpus: 1
        ram_gb: 1

  pack_light_2:
    cmd: python3 simulate_research.py pack_light_2
    deps:
      - simulate_research.py
    outs:
      - artifacts/pack_light_2.bin
    metrics:
      - metrics/pack_light_2.json:
          cache: false
    meta:
      cluster:
        workers:
          - HEC45803
        cpus: 1
        ram_gb: 1
