# Configuration de plafonnement systemd-journald pour Cluster-CI (Headnode)
# Empêche les journaux systemd de saturer le disque (plafond strict à 1 Go)

[Journal]
SystemMaxUse=1G
RuntimeMaxUse=200M
MaxRetentionSec=1month
Compress=yes
