# Configuration logrotate pour le journal de service Cluster-CI (Headnode)
# Assure la rotation et la compression du journal de service (cluster-ci-runs.log)
/home/*/cluster-ci/cluster-ci-runs.log {
    weekly
    rotate 4
    missingok
    notifempty
    compress
    delaycompress
    copytruncate
    maxsize 10M
}
