"""Module to realign dvc.lock code dependencies without full pipeline invalidation.

When only non-semantic code changes occur (or when explicitly requested via
--skip-code-invalidation / cluster-run-skip-code), this tool recalculates the MD5
hashes and sizes of code dependencies and writes them directly into dvc.lock
using ruamel.yaml to preserve exact formatting, comments, and structure.

Fail-fast invariants:
- Unknown stage -> ValueError
- Missing or malformed dvc.lock -> FileNotFoundError / ValueError
- Strict guardrails: NEVER alters output hashes ('outs') or non-code data dependencies.
- Detailed audit log of every realigned dependency (stage, path, old_md5, new_md5).
- Respects IS_LOCAL=1 for bot commits (never push for local jobs).
"""

import argparse
import hashlib
import logging
import os
import re
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Set, Tuple, Union

from ruamel.yaml import YAML

if hasattr(sys.stdout, "reconfigure"):
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

logger = logging.getLogger("cluster_ci.dvc_realign")

# Default classification rules
DEFAULT_CODE_EXTENSIONS: Set[str] = {
    ".py",
    ".sh",
    ".bash",
    ".r",
    ".jl",
    ".cu",
    ".cpp",
    ".c",
    ".h",
    ".hpp",
    ".rs",
    ".go",
}

DEFAULT_CODE_PATHS: Tuple[str, ...] = (
    "scripts/",
    "src/",
    "eval/",
    "code/",
    "lib/",
    "tests/",
)

EXCLUDED_DATA_PREFIXES: Tuple[str, ...] = (
    "data/",
    "dataset/",
    "datasets/",
)

EXCLUDED_DATA_EXTENSIONS: Set[str] = {
    ".csv",
    ".tsv",
    ".parquet",
    ".arrow",
    ".jsonl",
    ".json",
    ".yaml",
    ".yml",
    ".txt",
    ".pt",
    ".pth",
    ".bin",
    ".npy",
    ".npz",
    ".h5",
    ".hdf5",
    ".pkl",
    ".pickle",
    ".weights",
    ".safetensors",
    ".onnx",
}


def parse_code_directives_from_cluster_ci(
    repo_dir: Union[str, Path],
) -> Tuple[Optional[Set[str]], Optional[Tuple[str, ...]]]:
    """Parse CODE_EXTENSIONS and CODE_PATHS directives from .cluster-ci if present."""
    cluster_ci_path = Path(repo_dir) / ".cluster-ci"
    if not cluster_ci_path.is_file():
        return None, None

    code_exts: Optional[Set[str]] = None
    code_paths: Optional[Tuple[str, ...]] = None

    try:
        content = cluster_ci_path.read_text(encoding="utf-8", errors="replace")
        m_exts = re.search(r"^\s*CODE_EXTENSIONS\s*=\s*(.+)", content, re.MULTILINE)
        if m_exts:
            raw = m_exts.group(1).split("#")[0].strip().strip("\"'")
            items = [e.strip() if e.strip().startswith(".") else f".{e.strip()}" for e in re.split(r"[\s,]+", raw) if e.strip()]
            if items:
                code_exts = set(items)

        m_paths = re.search(r"^\s*CODE_PATHS\s*=\s*(.+)", content, re.MULTILINE)
        if m_paths:
            raw = m_paths.group(1).split("#")[0].strip().strip("\"'")
            items = [p.strip().rstrip("/") + "/" for p in re.split(r"[\s,]+", raw) if p.strip()]
            if items:
                code_paths = tuple(items)
    except Exception as e:
        logger.warning(f"Failed to read .cluster-ci directives: {e}")

    return code_exts, code_paths


def is_code_dependency(
    dep_path: str,
    code_extensions: Optional[Set[str]] = None,
    code_paths: Optional[Tuple[str, ...]] = None,
) -> bool:
    """Classify if a dependency path represents code/logic or data/hyperparameters.
    
    Returns True if dep_path is code or an AST hash, False if it is data or excluded.
    """
    norm = str(dep_path).replace("\\", "/").strip().lstrip("./")

    # 1. AST hash files generated by dvc-viewer are always code dependencies
    if norm.startswith(".dvc-viewer/hashes/") or norm.endswith(".hash"):
        return True

    # 2. Formal data and parameter exclusions (fail-safe)
    lower_norm = norm.lower()
    if lower_norm in ("params.yaml", "params.json", "params.toml"):
        return False

    for prefix in EXCLUDED_DATA_PREFIXES:
        if lower_norm.startswith(prefix) or f"/{prefix}" in lower_norm:
            return False

    suffix = Path(norm).suffix.lower()
    if suffix in EXCLUDED_DATA_EXTENSIONS:
        return False

    # 3. Code extensions check
    effective_exts = code_extensions if code_extensions is not None else DEFAULT_CODE_EXTENSIONS
    if suffix in effective_exts:
        return True

    # 4. Code directory prefixes check
    effective_paths = code_paths if code_paths is not None else DEFAULT_CODE_PATHS
    for path_prefix in effective_paths:
        if lower_norm.startswith(path_prefix.lower()):
            return True

    return False


def compute_file_md5_and_size(file_path: Union[str, Path]) -> Tuple[str, int]:
    """Calculate the MD5 hash (32-character hex) and size in bytes of a file on disk.
    
    Raises:
        FileNotFoundError: If file_path does not exist or is not a file.
    """
    path = Path(file_path)
    if path.is_dir():
        raise NotImplementedError(
            f"Directory dependency '{file_path}' is not supported for code realignment; "
            f"only file-level code dependencies are supported."
        )
    if not path.is_file():
        raise FileNotFoundError(f"Dependency file '{file_path}' does not exist on disk.")

    hasher = hashlib.md5()
    size = 0
    with open(path, "rb") as f:
        while True:
            chunk = f.read(65536)
            if not chunk:
                break
            hasher.update(chunk)
            size += len(chunk)

    return hasher.hexdigest(), size


def _get_yaml_instance() -> YAML:
    yaml = YAML()
    yaml.preserve_quotes = True
    yaml.indent(mapping=2, sequence=2, offset=0)
    return yaml


def realign_dvc_lock(
    repo_dir: Union[str, Path] = ".",
    target_stages: Optional[List[str]] = None,
    strict_guardrails: bool = True,
) -> List[Dict[str, Any]]:
    """Realign dvc.lock code dependency MD5 hashes with current workspace files.
    
    Args:
        repo_dir: Path to Git/DVC repository root.
        target_stages: Optional list of stage names to restrict realignment to.
        strict_guardrails: If True, reject realignment if non-code dependencies changed.
        
    Returns:
        List of recorded realignment changes (stage, path, old_md5, new_md5, old_size, new_size).
        
    Raises:
        FileNotFoundError: If dvc.lock, dvc.yaml, or a code dependency is missing.
        ValueError: If dvc.lock/dvc.yaml is malformed, target stage is unknown,
                    or non-code dependency changed under strict guardrails.
    """
    repo_path = Path(repo_dir).resolve()
    lock_file = repo_path / "dvc.lock"
    yaml_file = repo_path / "dvc.yaml"

    if not lock_file.is_file():
        raise FileNotFoundError(f"dvc.lock not found in repository at '{repo_path}'")
    if not yaml_file.is_file():
        raise FileNotFoundError(f"dvc.yaml not found in repository at '{repo_path}'")

    yaml = _get_yaml_instance()

    with open(lock_file, "r", encoding="utf-8") as f:
        lock_data = yaml.load(f)

    if not isinstance(lock_data, dict) or "stages" not in lock_data or not isinstance(lock_data["stages"], dict):
        raise ValueError(f"Malformed dvc.lock: missing or invalid 'stages' section in '{lock_file}'")

    with open(yaml_file, "r", encoding="utf-8") as f:
        yaml_data = yaml.load(f) or {}

    yaml_stages = set((yaml_data.get("stages") or {}).keys())

    # Validate target stages if supplied (Fail-Fast)
    if target_stages is not None:
        stages_to_process = []
        for s in target_stages:
            if s not in lock_data["stages"]:
                if s not in yaml_stages:
                    raise ValueError(f"Target stage '{s}' is unknown (not found in dvc.yaml or dvc.lock)")
                raise ValueError(f"Target stage '{s}' exists in dvc.yaml but has not been locked in dvc.lock yet")
            stages_to_process.append(s)
    else:
        stages_to_process = list(lock_data["stages"].keys())

    # Load custom directives from .cluster-ci if present
    custom_exts, custom_paths = parse_code_directives_from_cluster_ci(repo_path)

    changes: List[Dict[str, Any]] = []

    for stage_name in stages_to_process:
        stage_info = lock_data["stages"][stage_name]
        if not isinstance(stage_info, dict):
            raise ValueError(f"Malformed stage entry for '{stage_name}' in dvc.lock")

        # Invariant: NEVER touch output hashes ('outs')

        # Strict guardrails: Check parameters ('params')
        lock_params = stage_info.get("params") or {}
        if isinstance(lock_params, dict):
            for params_file_rel, param_entries in lock_params.items():
                if not isinstance(param_entries, dict):
                    continue
                abs_params_file = repo_path / params_file_rel
                if not abs_params_file.is_file():
                    if strict_guardrails:
                        raise FileNotFoundError(
                            f"Parameters file '{params_file_rel}' for stage '{stage_name}' "
                            f"does not exist on disk."
                        )
                    continue

                try:
                    with open(abs_params_file, "r", encoding="utf-8") as pf:
                        disk_params = yaml.load(pf) or {}
                except Exception as pe:
                    if strict_guardrails:
                        raise ValueError(
                            f"Strict guardrail rejection: Failed to parse parameters file "
                            f"'{params_file_rel}' for stage '{stage_name}': {pe}"
                        )
                    continue

                for param_key, expected_val in param_entries.items():
                    curr_val = disk_params
                    for part in param_key.split("."):
                        if isinstance(curr_val, dict) and part in curr_val:
                            curr_val = curr_val[part]
                        else:
                            curr_val = None
                            break
                    if curr_val is None and isinstance(disk_params, dict) and param_key in disk_params:
                        curr_val = disk_params[param_key]

                    if curr_val != expected_val:
                        if strict_guardrails:
                            raise ValueError(
                                f"Strict guardrail rejection: Parameter '{param_key}' in '{params_file_rel}' "
                                f"for stage '{stage_name}' has changed on disk (expected {expected_val!r}, got {curr_val!r}). "
                                f"Realigning code hashes is forbidden when parameters have changed."
                            )

        deps = stage_info.get("deps") or []
        for dep in deps:
            if not isinstance(dep, dict) or "path" not in dep:
                continue

            dep_rel_path = dep["path"]
            abs_dep_path = repo_path / dep_rel_path

            if abs_dep_path.is_dir() or dep_rel_path.endswith("/"):
                raise NotImplementedError(
                    f"Directory dependency '{dep_rel_path}' is not supported for code realignment; "
                    f"only file-level code dependencies are supported."
                )

            is_code = is_code_dependency(dep_rel_path, custom_exts, custom_paths)

            if is_code:
                if not abs_dep_path.is_file():
                    raise FileNotFoundError(
                        f"Code dependency '{dep_rel_path}' for stage '{stage_name}' not found on disk at '{abs_dep_path}'"
                    )

                curr_md5, curr_size = compute_file_md5_and_size(abs_dep_path)
                old_md5 = dep.get("md5")
                old_size = dep.get("size")

                if curr_md5 != old_md5 or curr_size != old_size:
                    dep["md5"] = curr_md5
                    dep["size"] = curr_size
                    change = {
                        "stage": stage_name,
                        "path": dep_rel_path,
                        "old_md5": old_md5,
                        "new_md5": curr_md5,
                        "old_size": old_size,
                        "new_size": curr_size,
                    }
                    changes.append(change)
                    print(
                        f"[dvc_realign] stage='{stage_name}' path='{dep_rel_path}' "
                        f"old_md5={old_md5} -> new_md5={curr_md5} (size {old_size} -> {curr_size})"
                    )
            else:
                # Non-code dependency (data, dataset, etc.)
                if abs_dep_path.is_file():
                    curr_data_md5, _ = compute_file_md5_and_size(abs_dep_path)
                    lock_data_md5 = dep.get("md5")
                    if lock_data_md5 and curr_data_md5 != lock_data_md5:
                        if strict_guardrails:
                            raise ValueError(
                                f"Strict guardrail rejection: Non-code dependency '{dep_rel_path}' "
                                f"in stage '{stage_name}' has changed on disk. "
                                f"Realigning code hashes is forbidden when data has changed."
                            )

    # Persist updated dvc.lock while preserving exact formatting
    if changes:
        with open(lock_file, "w", encoding="utf-8") as f:
            yaml.dump(lock_data, f)
        print(f"[dvc_realign] Successfully realigned {len(changes)} code dependency hash(es) in dvc.lock.")
    else:
        print("[dvc_realign] All code dependencies in dvc.lock are already up to date with workspace.")

    return changes


def commit_realigned_lock(
    repo_dir: Union[str, Path] = ".",
    changes: Optional[List[Dict[str, Any]]] = None,
    is_local: Optional[bool] = None,
) -> Optional[str]:
    """Commit realigned dvc.lock into Git, respecting local mode safeguards.
    
    If IS_LOCAL=1 or is_local=True, creates a local commit only without any git push.
    
    Returns:
        The created commit SHA, or None if no changes were committed.
    """
    if not changes:
        return None

    repo_path = Path(repo_dir).resolve()
    stages = sorted(list(set(c["stage"] for c in changes)))
    commit_msg = f"chore(ci): realign dvc.lock for code-only changes in {', '.join(stages)} [skip ci]"

    # Check git status of dvc.lock
    res_status = subprocess.run(
        ["git", "status", "--porcelain", "dvc.lock"],
        cwd=repo_path,
        capture_output=True,
        text=True,
    )
    if not res_status.stdout.strip():
        return None

    subprocess.run(["git", "add", "dvc.lock"], cwd=repo_path, check=True)
    subprocess.run(
        ["git", "commit", "-m", commit_msg],
        cwd=repo_path,
        check=True,
        capture_output=True,
    )

    res_sha = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=repo_path,
        capture_output=True,
        text=True,
        check=True,
    )
    commit_sha = res_sha.stdout.strip()

    # Guard: Check IS_LOCAL
    # Existing guard: IS_LOCAL=1 skips git push (JohannesDav commit 0358518 & dvc_iterative_repro.py:187)
    effective_is_local = is_local if is_local is not None else (os.environ.get("IS_LOCAL") == "1")
    if effective_is_local:
        print(f"[dvc_realign] [LOCAL] (IS_LOCAL=1): realigned dvc.lock committed locally ({commit_sha[:8]}), skipping Git push.")
    else:
        print(f"[dvc_realign] Realigned dvc.lock committed as {commit_sha[:8]} [skip ci].")

    return commit_sha


def main(argv: Optional[List[str]] = None) -> int:
    """CLI entry point for dvc_realign."""
    parser = argparse.ArgumentParser(
        description="Realign dvc.lock code dependencies without invalidating pipeline stages."
    )
    parser.add_argument(
        "--repo-dir",
        default=".",
        help="Path to repository containing dvc.yaml and dvc.lock (default: current directory)",
    )
    parser.add_argument(
        "--stages",
        nargs="*",
        default=None,
        help="Target stages to realign (default: all stages in dvc.lock)",
    )
    parser.add_argument(
        "--no-strict",
        action="store_true",
        help="Disable strict guardrails (do not abort if non-code dependencies changed)",
    )
    parser.add_argument(
        "--commit",
        action="store_true",
        help="Commit realigned dvc.lock to Git if changes were applied",
    )
    parser.add_argument(
        "--local",
        action="store_true",
        help="Explicitly mark execution as local mode (skip git push)",
    )

    args = parser.parse_args(argv)

    try:
        changes = realign_dvc_lock(
            repo_dir=args.repo_dir,
            target_stages=args.stages,
            strict_guardrails=not args.no_strict,
        )
        if args.commit and changes:
            commit_realigned_lock(
                repo_dir=args.repo_dir,
                changes=changes,
                is_local=args.local or (os.environ.get("IS_LOCAL") == "1"),
            )
        return 0
    except Exception as e:
        print(f"[dvc_realign] [ERROR] Error during dvc_realign: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
